// Code generated by protoc-gen-gogo.
// source: service.proto
// DO NOT EDIT!

/*
	Package service is a generated protocol buffer package.

	It is generated from these files:
		service.proto

	It has these top-level messages:
		IsReadyRsp
		GroupingReq
		GroupingRsp
		DataReq
		EmptyParams
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"

	grpc "github.com/grpc/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// is ready response
type IsReadyRsp struct {
	IsReady bool `protobuf:"varint,1,opt,name=isReady,proto3" json:"isReady,omitempty"`
}

func (m *IsReadyRsp) Reset()                    { *m = IsReadyRsp{} }
func (m *IsReadyRsp) String() string            { return proto.CompactTextString(m) }
func (*IsReadyRsp) ProtoMessage()               {}
func (*IsReadyRsp) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{0} }

func (m *IsReadyRsp) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

// grouping request
type GroupingReq struct {
	PeerIdx        int32 `protobuf:"varint,1,opt,name=peerIdx,proto3" json:"peerIdx,omitempty"`
	RcvID          int32 `protobuf:"varint,2,opt,name=rcvID,proto3" json:"rcvID,omitempty"`
	RcvParallelism int32 `protobuf:"varint,3,opt,name=rcvParallelism,proto3" json:"rcvParallelism,omitempty"`
	SndID          int32 `protobuf:"varint,4,opt,name=sndID,proto3" json:"sndID,omitempty"`
	StreamID       int32 `protobuf:"varint,5,opt,name=streamID,proto3" json:"streamID,omitempty"`
	GroupingType   int32 `protobuf:"varint,6,opt,name=groupingType,proto3" json:"groupingType,omitempty"`
}

func (m *GroupingReq) Reset()                    { *m = GroupingReq{} }
func (m *GroupingReq) String() string            { return proto.CompactTextString(m) }
func (*GroupingReq) ProtoMessage()               {}
func (*GroupingReq) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{1} }

func (m *GroupingReq) GetPeerIdx() int32 {
	if m != nil {
		return m.PeerIdx
	}
	return 0
}

func (m *GroupingReq) GetRcvID() int32 {
	if m != nil {
		return m.RcvID
	}
	return 0
}

func (m *GroupingReq) GetRcvParallelism() int32 {
	if m != nil {
		return m.RcvParallelism
	}
	return 0
}

func (m *GroupingReq) GetSndID() int32 {
	if m != nil {
		return m.SndID
	}
	return 0
}

func (m *GroupingReq) GetStreamID() int32 {
	if m != nil {
		return m.StreamID
	}
	return 0
}

func (m *GroupingReq) GetGroupingType() int32 {
	if m != nil {
		return m.GroupingType
	}
	return 0
}

// grouping response
type GroupingRsp struct {
	Parallelism int32 `protobuf:"varint,1,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
}

func (m *GroupingRsp) Reset()                    { *m = GroupingRsp{} }
func (m *GroupingRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupingRsp) ProtoMessage()               {}
func (*GroupingRsp) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{2} }

func (m *GroupingRsp) GetParallelism() int32 {
	if m != nil {
		return m.Parallelism
	}
	return 0
}

// data request
type DataReq struct {
	RcvID  int32  `protobuf:"varint,1,opt,name=rcvID,proto3" json:"rcvID,omitempty"`
	RcvIdx int32  `protobuf:"varint,2,opt,name=RcvIdx,proto3" json:"RcvIdx,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *DataReq) Reset()                    { *m = DataReq{} }
func (m *DataReq) String() string            { return proto.CompactTextString(m) }
func (*DataReq) ProtoMessage()               {}
func (*DataReq) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{3} }

func (m *DataReq) GetRcvID() int32 {
	if m != nil {
		return m.RcvID
	}
	return 0
}

func (m *DataReq) GetRcvIdx() int32 {
	if m != nil {
		return m.RcvIdx
	}
	return 0
}

func (m *DataReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DataReq) GetHashKey(srcPrallelism int, srcIndex int, dstPrallelism int) uint64 {
	return 0
}

// EmptyParams no params
type EmptyParams struct {
}

func (m *EmptyParams) Reset()                    { *m = EmptyParams{} }
func (m *EmptyParams) String() string            { return proto.CompactTextString(m) }
func (*EmptyParams) ProtoMessage()               {}
func (*EmptyParams) Descriptor() ([]byte, []int) { return fileDescriptorService, []int{4} }

func init() {
	proto.RegisterType((*IsReadyRsp)(nil), "service.IsReadyRsp")
	proto.RegisterType((*GroupingReq)(nil), "service.GroupingReq")
	proto.RegisterType((*GroupingRsp)(nil), "service.GroupingRsp")
	proto.RegisterType((*DataReq)(nil), "service.DataReq")
	proto.RegisterType((*EmptyParams)(nil), "service.EmptyParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IPCService service

type IPCServiceClient interface {
	Ping(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*EmptyParams, error)
	IsReady(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*IsReadyRsp, error)
	Grouping(ctx context.Context, in *GroupingReq, opts ...grpc.CallOption) (*GroupingRsp, error)
	SendData(ctx context.Context, opts ...grpc.CallOption) (IPCService_SendDataClient, error)
}

type iPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewIPCServiceClient(cc *grpc.ClientConn) IPCServiceClient {
	return &iPCServiceClient{cc}
}

func (c *iPCServiceClient) Ping(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*EmptyParams, error) {
	out := new(EmptyParams)
	err := grpc.Invoke(ctx, "/service.IPCService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPCServiceClient) IsReady(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*IsReadyRsp, error) {
	out := new(IsReadyRsp)
	err := grpc.Invoke(ctx, "/service.IPCService/IsReady", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPCServiceClient) Grouping(ctx context.Context, in *GroupingReq, opts ...grpc.CallOption) (*GroupingRsp, error) {
	out := new(GroupingRsp)
	err := grpc.Invoke(ctx, "/service.IPCService/Grouping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPCServiceClient) SendData(ctx context.Context, opts ...grpc.CallOption) (IPCService_SendDataClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_IPCService_serviceDesc.Streams[0], c.cc, "/service.IPCService/SendData", opts...)
	if err != nil {
		return nil, err
	}
	x := &iPCServiceSendDataClient{stream}
	return x, nil
}

type IPCService_SendDataClient interface {
	Send(*DataReq) error
	CloseAndRecv() (*EmptyParams, error)
	grpc.ClientStream
}

type iPCServiceSendDataClient struct {
	grpc.ClientStream
}

func (x *iPCServiceSendDataClient) Send(m *DataReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iPCServiceSendDataClient) CloseAndRecv() (*EmptyParams, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EmptyParams)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for IPCService service

type IPCServiceServer interface {
	Ping(context.Context, *EmptyParams) (*EmptyParams, error)
	IsReady(context.Context, *EmptyParams) (*IsReadyRsp, error)
	Grouping(context.Context, *GroupingReq) (*GroupingRsp, error)
	SendData(IPCService_SendDataServer) error
}

func RegisterIPCServiceServer(s *grpc.Server, srv IPCServiceServer) {
	s.RegisterService(&_IPCService_serviceDesc, srv)
}

func _IPCService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPCServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.IPCService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPCServiceServer).Ping(ctx, req.(*EmptyParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPCService_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPCServiceServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.IPCService/IsReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPCServiceServer).IsReady(ctx, req.(*EmptyParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPCService_Grouping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPCServiceServer).Grouping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.IPCService/Grouping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPCServiceServer).Grouping(ctx, req.(*GroupingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPCService_SendData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IPCServiceServer).SendData(&iPCServiceSendDataServer{stream})
}

type IPCService_SendDataServer interface {
	SendAndClose(*EmptyParams) error
	Recv() (*DataReq, error)
	grpc.ServerStream
}

type iPCServiceSendDataServer struct {
	grpc.ServerStream
}

func (x *iPCServiceSendDataServer) SendAndClose(m *EmptyParams) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iPCServiceSendDataServer) Recv() (*DataReq, error) {
	m := new(DataReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _IPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.IPCService",
	HandlerType: (*IPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _IPCService_Ping_Handler,
		},
		{
			MethodName: "IsReady",
			Handler:    _IPCService_IsReady_Handler,
		},
		{
			MethodName: "Grouping",
			Handler:    _IPCService_Grouping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendData",
			Handler:       _IPCService_SendData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}

func (m *IsReadyRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IsReadyRsp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IsReady {
		dAtA[i] = 0x8
		i++
		if m.IsReady {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *GroupingReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupingReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.PeerIdx != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintService(dAtA, i, uint64(m.PeerIdx))
	}
	if m.RcvID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintService(dAtA, i, uint64(m.RcvID))
	}
	if m.RcvParallelism != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintService(dAtA, i, uint64(m.RcvParallelism))
	}
	if m.SndID != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintService(dAtA, i, uint64(m.SndID))
	}
	if m.StreamID != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintService(dAtA, i, uint64(m.StreamID))
	}
	if m.GroupingType != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintService(dAtA, i, uint64(m.GroupingType))
	}
	return i, nil
}

func (m *GroupingRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupingRsp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Parallelism != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Parallelism))
	}
	return i, nil
}

func (m *DataReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RcvID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintService(dAtA, i, uint64(m.RcvID))
	}
	if m.RcvIdx != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintService(dAtA, i, uint64(m.RcvIdx))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintService(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *EmptyParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyParams) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeFixed64Service(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Service(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *IsReadyRsp) Size() (n int) {
	var l int
	_ = l
	if m.IsReady {
		n += 2
	}
	return n
}

func (m *GroupingReq) Size() (n int) {
	var l int
	_ = l
	if m.PeerIdx != 0 {
		n += 1 + sovService(uint64(m.PeerIdx))
	}
	if m.RcvID != 0 {
		n += 1 + sovService(uint64(m.RcvID))
	}
	if m.RcvParallelism != 0 {
		n += 1 + sovService(uint64(m.RcvParallelism))
	}
	if m.SndID != 0 {
		n += 1 + sovService(uint64(m.SndID))
	}
	if m.StreamID != 0 {
		n += 1 + sovService(uint64(m.StreamID))
	}
	if m.GroupingType != 0 {
		n += 1 + sovService(uint64(m.GroupingType))
	}
	return n
}

func (m *GroupingRsp) Size() (n int) {
	var l int
	_ = l
	if m.Parallelism != 0 {
		n += 1 + sovService(uint64(m.Parallelism))
	}
	return n
}

func (m *DataReq) Size() (n int) {
	var l int
	_ = l
	if m.RcvID != 0 {
		n += 1 + sovService(uint64(m.RcvID))
	}
	if m.RcvIdx != 0 {
		n += 1 + sovService(uint64(m.RcvIdx))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *EmptyParams) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IsReadyRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IsReadyRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IsReadyRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsReady", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsReady = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GroupingReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupingReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupingReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerIdx", wireType)
			}
			m.PeerIdx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeerIdx |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RcvID", wireType)
			}
			m.RcvID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RcvID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RcvParallelism", wireType)
			}
			m.RcvParallelism = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RcvParallelism |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SndID", wireType)
			}
			m.SndID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SndID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamID", wireType)
			}
			m.StreamID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupingType", wireType)
			}
			m.GroupingType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupingType |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GroupingRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupingRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupingRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parallelism", wireType)
			}
			m.Parallelism = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Parallelism |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RcvID", wireType)
			}
			m.RcvID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RcvID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RcvIdx", wireType)
			}
			m.RcvIdx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RcvIdx |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmptyParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("service.proto", fileDescriptorService) }

var fileDescriptorService = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0x1d, 0x6d, 0x9b, 0xf0, 0xda, 0x4a, 0x79, 0x16, 0x09, 0x5d, 0x84, 0x92, 0x45, 0xe9,
	0xaa, 0x42, 0x2d, 0x1e, 0x40, 0x23, 0x12, 0xdc, 0x94, 0xa9, 0x17, 0x88, 0xc9, 0x50, 0x02, 0x4d,
	0x3a, 0xce, 0xc4, 0x60, 0x6f, 0xe2, 0x5d, 0xbc, 0x80, 0x4b, 0x8f, 0x20, 0xd5, 0x83, 0xc8, 0x4c,
	0xfe, 0x30, 0x4a, 0xdd, 0xe5, 0xfb, 0xde, 0xfb, 0xe0, 0xfd, 0xe6, 0x0b, 0xf4, 0x25, 0x13, 0x45,
	0x12, 0xb1, 0x19, 0x17, 0xdb, 0x7c, 0x8b, 0x56, 0x25, 0xbd, 0x09, 0x40, 0x20, 0x29, 0x0b, 0xe3,
	0x1d, 0x95, 0x1c, 0x1d, 0xb0, 0x92, 0x52, 0x39, 0x64, 0x4c, 0xa6, 0x36, 0xad, 0xa5, 0xf7, 0x46,
	0xa0, 0x7b, 0x27, 0xb6, 0xcf, 0x3c, 0xc9, 0xd6, 0x94, 0x3d, 0xa9, 0x4d, 0xce, 0x98, 0x08, 0xe2,
	0x17, 0xbd, 0xd9, 0xa6, 0xb5, 0xc4, 0x21, 0xb4, 0x45, 0x54, 0x04, 0xbe, 0x73, 0xac, 0xfd, 0x52,
	0xe0, 0x04, 0x4e, 0x45, 0x54, 0x2c, 0x43, 0x11, 0x6e, 0x36, 0x6c, 0x93, 0xc8, 0xd4, 0x39, 0xd1,
	0xe3, 0x3f, 0xae, 0x4a, 0xcb, 0x2c, 0x0e, 0x7c, 0xa7, 0x55, 0xa6, 0xb5, 0xc0, 0x11, 0xd8, 0x32,
	0x17, 0x2c, 0x4c, 0x03, 0xdf, 0x69, 0xeb, 0x41, 0xa3, 0xd1, 0x83, 0xde, 0xba, 0x3a, 0xec, 0x61,
	0xc7, 0x99, 0xd3, 0xd1, 0xf3, 0x5f, 0x9e, 0x77, 0x61, 0x1c, 0x2f, 0x39, 0x8e, 0xa1, 0xcb, 0x8d,
	0x4b, 0x4a, 0x00, 0xd3, 0xf2, 0xee, 0xc1, 0xf2, 0xc3, 0x3c, 0x54, 0xa4, 0x0d, 0x0f, 0x31, 0x79,
	0xce, 0xa1, 0x43, 0xa3, 0x42, 0xe1, 0x97, 0x98, 0x95, 0x42, 0x84, 0x96, 0x0a, 0x6a, 0xba, 0x1e,
	0xd5, 0xdf, 0x5e, 0x1f, 0xba, 0xb7, 0x29, 0xcf, 0x77, 0x8a, 0x33, 0x95, 0xf3, 0x6f, 0x02, 0x10,
	0x2c, 0x6f, 0x56, 0x65, 0x03, 0x38, 0x87, 0xd6, 0x32, 0xc9, 0xd6, 0x38, 0x9c, 0xd5, 0x15, 0x19,
	0xcb, 0xa3, 0x83, 0x2e, 0x2e, 0xc0, 0xaa, 0x5a, 0xfb, 0x27, 0x76, 0xd6, 0xb8, 0x46, 0xbb, 0x57,
	0x60, 0xd7, 0xaf, 0x60, 0xc4, 0x8c, 0x56, 0x47, 0x07, 0x5c, 0xc9, 0x71, 0x01, 0xf6, 0x8a, 0x65,
	0xb1, 0x62, 0xc1, 0x41, 0xb3, 0x51, 0xbd, 0xcf, 0xe1, 0x0b, 0xa7, 0xe4, 0x7a, 0xf0, 0xbe, 0x77,
	0xc9, 0xc7, 0xde, 0x25, 0x9f, 0x7b, 0x97, 0xbc, 0x7e, 0xb9, 0x47, 0x8f, 0x1d, 0xfd, 0xef, 0x5d,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xec, 0xdd, 0x84, 0x12, 0x8c, 0x02, 0x00, 0x00,
}
